// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtC8kNcWwaCjXAZV5c65vhDNZ3_1ItHPQ',
    appId: '1:421926019004:web:a4e3a4808e6a47aeaa55b9',
    messagingSenderId: '421926019004',
    projectId: 'toystore-da9ec',
    authDomain: 'toystore-da9ec.firebaseapp.com',
    storageBucket: 'toystore-da9ec.appspot.com',
    measurementId: 'G-PRHZ5ZBHRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVoGM9n-C9JU3odkqRoRGxNcQHWO5yZg',
    appId: '1:421926019004:android:dfdc068160809db9aa55b9',
    messagingSenderId: '421926019004',
    projectId: 'toystore-da9ec',
    storageBucket: 'toystore-da9ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIOmb7_33H7NqYbLDCB19pAaq4Kc4WYtU',
    appId: '1:421926019004:ios:46a72826332eea18aa55b9',
    messagingSenderId: '421926019004',
    projectId: 'toystore-da9ec',
    storageBucket: 'toystore-da9ec.appspot.com',
    iosClientId: '421926019004-pqr8nlnbgb1dmhml8l62e7iq2lgvl0a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.toyCheckout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIOmb7_33H7NqYbLDCB19pAaq4Kc4WYtU',
    appId: '1:421926019004:ios:46a72826332eea18aa55b9',
    messagingSenderId: '421926019004',
    projectId: 'toystore-da9ec',
    storageBucket: 'toystore-da9ec.appspot.com',
    iosClientId: '421926019004-pqr8nlnbgb1dmhml8l62e7iq2lgvl0a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.toyCheckout',
  );
}
